server:
  forward-headers-strategy: native
spring:
  application:
    name: dopdang
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2   # 최소 커넥션 수
      maximum-pool-size: 5  # 최대 커넥션 수

  jackson:
    time-zone: Asia/Seoul

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

    aws:
      credentials:
        access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
        secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      region:
        static: ${CLOUD_AWS_REGION}

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope:
              - profile
              - email
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope:
              - name
              - email
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    root: info

common:
  api:
    base-url: 'http://localhost:8080'

payment:
  fee:
    rate: 0.1  # 결제 수수료율 10%
  toss:
    secretKey: ${TOSS_SECRET_KEY}
    api-url: https://api.tosspayments.com
    elasticsearch:
      uris: http://localhost:9200

coolsms:
  api_key: ${COOLSMS_API_KEY}
  api_secret: ${COOLSMS_API_SECRET}
  from_number: ${COOLSMS_FROM_NUMBER}

jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration: ${JWT_ACCESS_EXPIRATION}
    refresh-expiration: ${JWT_REFRESH_EXPIRATION}

site:
  url:
    frontend: "http://localhost:3000"

springdoc: { swagger-ui: { path: /swagger-ui.html, groups-order: DESC, operationsSorter: method, disable-swagger-default-url: true, display-request-duration: true }, api-docs: { path: /api-docs }, show-actuator: true, default-consumes-media-type: application/json, default-produces-media-type: application/json }

service:
  key: ${SERVICE_KEY}
