spring:
  application:
    name: dopdang

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
      password: ${REDIS_PASSWORD}

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

common:
  api:
    base-url: 'http://localhost:8080'


payment:
  fee:
    rate: 0.1  # 결제 수수료율 10%
  toss:
    secretKey: ${TOSS_SECRET_KEY}
    api-url: https://api.tosspayments.com